#!/bin/bash

if [ "$1" == "init" ]; then
    mkdir -p bin/ bin/obj/ bin/moc/
    qmake
elif [ "$1" == "build" ]; then
    if [ -f Makefile ]; then
        make
    else
        echo "Makefile not found. Run: \"$0 init\""
    fi
elif [ "$1" == "clean" ]; then
    if [ -d bin/ ]; then
        rm -r bin/
    fi
    echo "Cleanup."
elif [ "$1" == "clean_all" ]; then
    if [ -f Makefile ]; then
        make distclean
    fi
    if [ -d bin/ ]; then
        rm -r bin/
    fi
    echo "Cleanup all."
else
    echo "Usage: $0 [init|build|clean|clean_all]"
    echo "- init:      Inizialize the Qt project and create the Makefile."
    echo "- build:     Build the project creating the executable."
    echo "- clean:     Clean the executable and the object files."
    echo "- clean_all: Clean all the files generated by the \"init\" and \"build\" commands."
fi
